
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATERTHAN = 38;
  public static final int STRING_LITERAL = 45;
  public static final int LBRACKET = 39;
  public static final int C_PAREN = 33;
  public static final int O_PAREN = 32;
  public static final int NOTEQUAL = 31;
  public static final int INT = 18;
  public static final int PRINTLN = 17;
  public static final int O_CBRACKET = 34;
  public static final int MINUS = 24;
  public static final int STATIC = 4;
  public static final int SEMICOLON = 36;
  public static final int NOT = 27;
  public static final int AND = 28;
  public static final int LESSTHAN = 37;
  public static final int OR = 29;
  public static final int COMMA = 41;
  public static final int CLASS = 7;
  public static final int DIV = 26;
  public static final int PLUS = 22;
  public static final int MAIN = 6;
  public static final int IF = 14;
  public static final int THIS = 8;
  public static final int DOT = 42;
  public static final int EOF = 0;
  public static final int BOOLEAN = 19;
  public static final int RETURN = 21;
  public static final int RBRACKET = 40;
  public static final int EQUAL = 30;
  public static final int TRUE = 12;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int NULL = 11;
  public static final int VOID = 5;
  public static final int EQ = 23;
  public static final int TIMES = 25;
  public static final int ELSE = 15;
  public static final int C_CBRACKET = 35;
  public static final int WHILE = 16;
  public static final int PUBLIC = 3;
  public static final int EXTENDS = 2;
  public static final int STRING = 20;
  public static final int FALSE = 13;
  public static final int LENGTH = 10;
  public static final int INTEGER_LITERAL = 44;
  public static final int IDENTIFIER = 43;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EXTENDS",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "CLASS",
  "THIS",
  "NEW",
  "LENGTH",
  "NULL",
  "TRUE",
  "FALSE",
  "IF",
  "ELSE",
  "WHILE",
  "PRINTLN",
  "INT",
  "BOOLEAN",
  "STRING",
  "RETURN",
  "PLUS",
  "EQ",
  "MINUS",
  "TIMES",
  "DIV",
  "NOT",
  "AND",
  "OR",
  "EQUAL",
  "NOTEQUAL",
  "O_PAREN",
  "C_PAREN",
  "O_CBRACKET",
  "C_CBRACKET",
  "SEMICOLON",
  "LESSTHAN",
  "GREATERTHAN",
  "LBRACKET",
  "RBRACKET",
  "COMMA",
  "DOT",
  "IDENTIFIER",
  "INTEGER_LITERAL",
  "STRING_LITERAL"
  };
}

